services:
  - type: web
    name: personal-finance-manager
    env: java
    plan: free
    buildCommand: "./apache-maven-3.9.6/bin/mvn.cmd clean install -DskipTests"
    startCommand: "java -jar target/personal-finance-manager-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
